# End your baseURL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL = "https://orientrcu.github.io/orientrcu_blog"
relativeURLs = true

languageCode = "en-us"
title = "Blog"
theme = "hugo-theme-one"
googleAnalytics = "UA-65383716-5"

# Chroma Syntax Highlighting
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["archives.md"]

